### PR TITLE
Update issue template to newer style

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@brookhong @jgkamat please review

**Comment by jgkamat** [comment]
Sorry, I'm not familiar with github specific features in general, so I can't 
comment on this too much.

This page suggests this change might need a config.yml to go with it, but I'm 
not sure what's actually needed:

https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

**Comment by gliptak** [comment]
It is simply a rename of the existing file (I generated the new location in one of my repos)

**Comment by brookhong** [comment]
Thanks, could you please describe more about the change?

I only see what the change is,  but don't understand why.

**Comment by gliptak** [comment]
This intends to correct the yellow warning displaying at the top of https://github.com/brookhong/Surfingkeys/blob/master/.github/ISSUE_TEMPLATE.md

**Pull request merged**
