### PR TITLE
Feature/symbol spacer

### PR DESCRIPTION
**Pull request by simonwjackson**
I wanted the ability to add some padding to the separator symbol (≫)

### CODE REVIEW

**Comment by brookhong** [comment]
You could achieve that by adding below in your settings:

    settings.theme = `
        #sk_omnibarSearchArea .prompt {
            padding-right: 20px;
        }
    }`;

**Comment by simonwjackson** [comment]
For the right side, yes. But, between the separator and its label, currently there isn't a way to add spacing.

```html
<span class="prompt">google≫</span>
```

**Comment by brookhong** [comment]
It makes sense, then please remove below two json files from this PR.

* .vscode/settings.json
* package-lock.json

**Comment by simonwjackson** [comment]
By the way, what version of node & npm are you using to build?
I want to make sure I'm using the same version.

npm recommends [including this in the repo](https://stackoverflow.com/a/44210813) since version 5

**Comment by brookhong** [comment]
This is not a real node package, I only use npm for build.

**Pull request merged**
