### PR TITLE
Add Github Actions npm build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

An example build at:

https://github.com/gliptak/Surfingkeys/pull/1/checks?check_run_id=334164071

Enable Actions at

https://github.com/brookhong/Surfingkeys/actions

### CODE REVIEW

**Comment by gliptak** [comment]
@brookhong please review

**Comment by brookhong** [comment]
Thanks.

**Comment by gliptak** [comment]
@brookhong PR build show up at https://github.com/brookhong/Surfingkeys/actions but the PRs https://github.com/brookhong/Surfingkeys/pulls don't seem to have the build checkmarks.

Could you check the actions settings?

**Comment by brookhong** [comment]
There are build checkmarks for PR, for example, https://github.com/brookhong/Surfingkeys/pull/1143/checks

What you see on https://github.com/brookhong/Surfingkeys/pulls are those old PRs which were sent before this action was set.

**Comment by gliptak** [comment]
@brookhong got it. Thanks for the pointer

**Pull request merged**
